server:
  port: 9886
spring:
  application:
    name: JobNotificationApplication
  datasource:
    url: jdbc:mysql://localhost:3306/job_notifications
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true